/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiStartHermesRouteImport } from './routes/api/start-hermes'
import { Route as ApiStartAgentRouteImport } from './routes/api/start-agent'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiLocalProvidersRouteImport } from './routes/api/local-providers'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHermesTasksAssigneesRouteImport } from './routes/api/hermes-tasks-assignees'
import { Route as ApiHermesTasksRouteImport } from './routes/api/hermes-tasks'
import { Route as ApiHermesJobsRouteImport } from './routes/api/hermes-jobs'
import { Route as ApiHermesConfigRouteImport } from './routes/api/hermes-config'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway-status'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiCrewStatusRouteImport } from './routes/api/crew-status'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiConductorStopRouteImport } from './routes/api/conductor-stop'
import { Route as ApiConductorSpawnRouteImport } from './routes/api/conductor-spawn'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiSkillsUninstallRouteImport } from './routes/api/skills/uninstall'
import { Route as ApiSkillsToggleRouteImport } from './routes/api/skills/toggle'
import { Route as ApiSkillsInstallRouteImport } from './routes/api/skills/install'
import { Route as ApiSkillsHubSearchRouteImport } from './routes/api/skills/hub-search'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiProfilesRenameRouteImport } from './routes/api/profiles/rename'
import { Route as ApiProfilesReadRouteImport } from './routes/api/profiles/read'
import { Route as ApiProfilesListRouteImport } from './routes/api/profiles/list'
import { Route as ApiProfilesDeleteRouteImport } from './routes/api/profiles/delete'
import { Route as ApiProfilesCreateRouteImport } from './routes/api/profiles/create'
import { Route as ApiProfilesActivateRouteImport } from './routes/api/profiles/activate'
import { Route as ApiOauthPollTokenRouteImport } from './routes/api/oauth.poll-token'
import { Route as ApiOauthDeviceCodeRouteImport } from './routes/api/oauth.device-code'
import { Route as ApiModelInfoRouteImport } from './routes/api/model/info'
import { Route as ApiMemoryWriteRouteImport } from './routes/api/memory/write'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryReadRouteImport } from './routes/api/memory/read'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiMcpReloadRouteImport } from './routes/api/mcp/reload'
import { Route as ApiKnowledgeSyncRouteImport } from './routes/api/knowledge/sync'
import { Route as ApiKnowledgeSearchRouteImport } from './routes/api/knowledge/search'
import { Route as ApiKnowledgeReadRouteImport } from './routes/api/knowledge/read'
import { Route as ApiKnowledgeListRouteImport } from './routes/api/knowledge/list'
import { Route as ApiKnowledgeGraphRouteImport } from './routes/api/knowledge/graph'
import { Route as ApiKnowledgeConfigRouteImport } from './routes/api/knowledge/config'
import { Route as ApiHermesTasksTaskIdRouteImport } from './routes/api/hermes-tasks.$taskId'
import { Route as ApiHermesProxySplatRouteImport } from './routes/api/hermes-proxy/$'
import { Route as ApiHermesJobsJobIdRouteImport } from './routes/api/hermes-jobs.$jobId'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'
import { Route as ApiSessionsSessionKeyActiveRunRouteImport } from './routes/api/sessions/$sessionKey.active-run'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartHermesRoute = ApiStartHermesRouteImport.update({
  id: '/api/start-hermes',
  path: '/api/start-hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartAgentRoute = ApiStartAgentRouteImport.update({
  id: '/api/start-agent',
  path: '/api/start-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalProvidersRoute = ApiLocalProvidersRouteImport.update({
  id: '/api/local-providers',
  path: '/api/local-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksAssigneesRoute = ApiHermesTasksAssigneesRouteImport.update({
  id: '/api/hermes-tasks-assignees',
  path: '/api/hermes-tasks-assignees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksRoute = ApiHermesTasksRouteImport.update({
  id: '/api/hermes-tasks',
  path: '/api/hermes-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsRoute = ApiHermesJobsRouteImport.update({
  id: '/api/hermes-jobs',
  path: '/api/hermes-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesConfigRoute = ApiHermesConfigRouteImport.update({
  id: '/api/hermes-config',
  path: '/api/hermes-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway-status',
  path: '/api/gateway-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewStatusRoute = ApiCrewStatusRouteImport.update({
  id: '/api/crew-status',
  path: '/api/crew-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConductorStopRoute = ApiConductorStopRouteImport.update({
  id: '/api/conductor-stop',
  path: '/api/conductor-stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConductorSpawnRoute = ApiConductorSpawnRouteImport.update({
  id: '/api/conductor-spawn',
  path: '/api/conductor-spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsUninstallRoute = ApiSkillsUninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsToggleRoute = ApiSkillsToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsInstallRoute = ApiSkillsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsHubSearchRoute = ApiSkillsHubSearchRouteImport.update({
  id: '/hub-search',
  path: '/hub-search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiProfilesRenameRoute = ApiProfilesRenameRouteImport.update({
  id: '/api/profiles/rename',
  path: '/api/profiles/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesReadRoute = ApiProfilesReadRouteImport.update({
  id: '/api/profiles/read',
  path: '/api/profiles/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesListRoute = ApiProfilesListRouteImport.update({
  id: '/api/profiles/list',
  path: '/api/profiles/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesDeleteRoute = ApiProfilesDeleteRouteImport.update({
  id: '/api/profiles/delete',
  path: '/api/profiles/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesCreateRoute = ApiProfilesCreateRouteImport.update({
  id: '/api/profiles/create',
  path: '/api/profiles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesActivateRoute = ApiProfilesActivateRouteImport.update({
  id: '/api/profiles/activate',
  path: '/api/profiles/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthPollTokenRoute = ApiOauthPollTokenRouteImport.update({
  id: '/api/oauth/poll-token',
  path: '/api/oauth/poll-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDeviceCodeRoute = ApiOauthDeviceCodeRouteImport.update({
  id: '/api/oauth/device-code',
  path: '/api/oauth/device-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelInfoRoute = ApiModelInfoRouteImport.update({
  id: '/api/model/info',
  path: '/api/model/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryWriteRoute = ApiMemoryWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryReadRoute = ApiMemoryReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpReloadRoute = ApiMcpReloadRouteImport.update({
  id: '/api/mcp/reload',
  path: '/api/mcp/reload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSyncRoute = ApiKnowledgeSyncRouteImport.update({
  id: '/api/knowledge/sync',
  path: '/api/knowledge/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSearchRoute = ApiKnowledgeSearchRouteImport.update({
  id: '/api/knowledge/search',
  path: '/api/knowledge/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeReadRoute = ApiKnowledgeReadRouteImport.update({
  id: '/api/knowledge/read',
  path: '/api/knowledge/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeListRoute = ApiKnowledgeListRouteImport.update({
  id: '/api/knowledge/list',
  path: '/api/knowledge/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeGraphRoute = ApiKnowledgeGraphRouteImport.update({
  id: '/api/knowledge/graph',
  path: '/api/knowledge/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeConfigRoute = ApiKnowledgeConfigRouteImport.update({
  id: '/api/knowledge/config',
  path: '/api/knowledge/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksTaskIdRoute = ApiHermesTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiHermesTasksRoute,
} as any)
const ApiHermesProxySplatRoute = ApiHermesProxySplatRouteImport.update({
  id: '/api/hermes-proxy/$',
  path: '/api/hermes-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsJobIdRoute = ApiHermesJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiHermesJobsRoute,
} as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiSessionsSessionKeyActiveRunRoute =
  ApiSessionsSessionKeyActiveRunRouteImport.update({
    id: '/$sessionKey/active-run',
    path: '/$sessionKey/active-run',
    getParentRoute: () => ApiSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat'
    | '/settings'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ConductorRoute: typeof ConductorRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  OperationsRoute: typeof OperationsRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  TerminalRoute: typeof TerminalRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiConductorSpawnRoute: typeof ApiConductorSpawnRoute
  ApiConductorStopRoute: typeof ApiConductorStopRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiCrewStatusRoute: typeof ApiCrewStatusRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiHermesConfigRoute: typeof ApiHermesConfigRoute
  ApiHermesJobsRoute: typeof ApiHermesJobsRouteWithChildren
  ApiHermesTasksRoute: typeof ApiHermesTasksRouteWithChildren
  ApiHermesTasksAssigneesRoute: typeof ApiHermesTasksAssigneesRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiLocalProvidersRoute: typeof ApiLocalProvidersRoute
  ApiMemoryRoute: typeof ApiMemoryRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiStartAgentRoute: typeof ApiStartAgentRoute
  ApiStartHermesRoute: typeof ApiStartHermesRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiHermesProxySplatRoute: typeof ApiHermesProxySplatRoute
  ApiKnowledgeConfigRoute: typeof ApiKnowledgeConfigRoute
  ApiKnowledgeGraphRoute: typeof ApiKnowledgeGraphRoute
  ApiKnowledgeListRoute: typeof ApiKnowledgeListRoute
  ApiKnowledgeReadRoute: typeof ApiKnowledgeReadRoute
  ApiKnowledgeSearchRoute: typeof ApiKnowledgeSearchRoute
  ApiKnowledgeSyncRoute: typeof ApiKnowledgeSyncRoute
  ApiMcpReloadRoute: typeof ApiMcpReloadRoute
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiModelInfoRoute: typeof ApiModelInfoRoute
  ApiOauthDeviceCodeRoute: typeof ApiOauthDeviceCodeRoute
  ApiOauthPollTokenRoute: typeof ApiOauthPollTokenRoute
  ApiProfilesActivateRoute: typeof ApiProfilesActivateRoute
  ApiProfilesCreateRoute: typeof ApiProfilesCreateRoute
  ApiProfilesDeleteRoute: typeof ApiProfilesDeleteRoute
  ApiProfilesListRoute: typeof ApiProfilesListRoute
  ApiProfilesReadRoute: typeof ApiProfilesReadRoute
  ApiProfilesRenameRoute: typeof ApiProfilesRenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-hermes': {
      id: '/api/start-hermes'
      path: '/api/start-hermes'
      fullPath: '/api/start-hermes'
      preLoaderRoute: typeof ApiStartHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-agent': {
      id: '/api/start-agent'
      path: '/api/start-agent'
      fullPath: '/api/start-agent'
      preLoaderRoute: typeof ApiStartAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-providers': {
      id: '/api/local-providers'
      path: '/api/local-providers'
      fullPath: '/api/local-providers'
      preLoaderRoute: typeof ApiLocalProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks-assignees': {
      id: '/api/hermes-tasks-assignees'
      path: '/api/hermes-tasks-assignees'
      fullPath: '/api/hermes-tasks-assignees'
      preLoaderRoute: typeof ApiHermesTasksAssigneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks': {
      id: '/api/hermes-tasks'
      path: '/api/hermes-tasks'
      fullPath: '/api/hermes-tasks'
      preLoaderRoute: typeof ApiHermesTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs': {
      id: '/api/hermes-jobs'
      path: '/api/hermes-jobs'
      fullPath: '/api/hermes-jobs'
      preLoaderRoute: typeof ApiHermesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-config': {
      id: '/api/hermes-config'
      path: '/api/hermes-config'
      fullPath: '/api/hermes-config'
      preLoaderRoute: typeof ApiHermesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-status': {
      id: '/api/gateway-status'
      path: '/api/gateway-status'
      fullPath: '/api/gateway-status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew-status': {
      id: '/api/crew-status'
      path: '/api/crew-status'
      fullPath: '/api/crew-status'
      preLoaderRoute: typeof ApiCrewStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conductor-stop': {
      id: '/api/conductor-stop'
      path: '/api/conductor-stop'
      fullPath: '/api/conductor-stop'
      preLoaderRoute: typeof ApiConductorStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conductor-spawn': {
      id: '/api/conductor-spawn'
      path: '/api/conductor-spawn'
      fullPath: '/api/conductor-spawn'
      preLoaderRoute: typeof ApiConductorSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/uninstall': {
      id: '/api/skills/uninstall'
      path: '/uninstall'
      fullPath: '/api/skills/uninstall'
      preLoaderRoute: typeof ApiSkillsUninstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/toggle': {
      id: '/api/skills/toggle'
      path: '/toggle'
      fullPath: '/api/skills/toggle'
      preLoaderRoute: typeof ApiSkillsToggleRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/install': {
      id: '/api/skills/install'
      path: '/install'
      fullPath: '/api/skills/install'
      preLoaderRoute: typeof ApiSkillsInstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/hub-search': {
      id: '/api/skills/hub-search'
      path: '/hub-search'
      fullPath: '/api/skills/hub-search'
      preLoaderRoute: typeof ApiSkillsHubSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/profiles/rename': {
      id: '/api/profiles/rename'
      path: '/api/profiles/rename'
      fullPath: '/api/profiles/rename'
      preLoaderRoute: typeof ApiProfilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/read': {
      id: '/api/profiles/read'
      path: '/api/profiles/read'
      fullPath: '/api/profiles/read'
      preLoaderRoute: typeof ApiProfilesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/list': {
      id: '/api/profiles/list'
      path: '/api/profiles/list'
      fullPath: '/api/profiles/list'
      preLoaderRoute: typeof ApiProfilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/delete': {
      id: '/api/profiles/delete'
      path: '/api/profiles/delete'
      fullPath: '/api/profiles/delete'
      preLoaderRoute: typeof ApiProfilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/create': {
      id: '/api/profiles/create'
      path: '/api/profiles/create'
      fullPath: '/api/profiles/create'
      preLoaderRoute: typeof ApiProfilesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/activate': {
      id: '/api/profiles/activate'
      path: '/api/profiles/activate'
      fullPath: '/api/profiles/activate'
      preLoaderRoute: typeof ApiProfilesActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/poll-token': {
      id: '/api/oauth/poll-token'
      path: '/api/oauth/poll-token'
      fullPath: '/api/oauth/poll-token'
      preLoaderRoute: typeof ApiOauthPollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/device-code': {
      id: '/api/oauth/device-code'
      path: '/api/oauth/device-code'
      fullPath: '/api/oauth/device-code'
      preLoaderRoute: typeof ApiOauthDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/info': {
      id: '/api/model/info'
      path: '/api/model/info'
      fullPath: '/api/model/info'
      preLoaderRoute: typeof ApiModelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/write': {
      id: '/api/memory/write'
      path: '/write'
      fullPath: '/api/memory/write'
      preLoaderRoute: typeof ApiMemoryWriteRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/read': {
      id: '/api/memory/read'
      path: '/read'
      fullPath: '/api/memory/read'
      preLoaderRoute: typeof ApiMemoryReadRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/reload': {
      id: '/api/mcp/reload'
      path: '/api/mcp/reload'
      fullPath: '/api/mcp/reload'
      preLoaderRoute: typeof ApiMcpReloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/sync': {
      id: '/api/knowledge/sync'
      path: '/api/knowledge/sync'
      fullPath: '/api/knowledge/sync'
      preLoaderRoute: typeof ApiKnowledgeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/search': {
      id: '/api/knowledge/search'
      path: '/api/knowledge/search'
      fullPath: '/api/knowledge/search'
      preLoaderRoute: typeof ApiKnowledgeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/read': {
      id: '/api/knowledge/read'
      path: '/api/knowledge/read'
      fullPath: '/api/knowledge/read'
      preLoaderRoute: typeof ApiKnowledgeReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/list': {
      id: '/api/knowledge/list'
      path: '/api/knowledge/list'
      fullPath: '/api/knowledge/list'
      preLoaderRoute: typeof ApiKnowledgeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/graph': {
      id: '/api/knowledge/graph'
      path: '/api/knowledge/graph'
      fullPath: '/api/knowledge/graph'
      preLoaderRoute: typeof ApiKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/config': {
      id: '/api/knowledge/config'
      path: '/api/knowledge/config'
      fullPath: '/api/knowledge/config'
      preLoaderRoute: typeof ApiKnowledgeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks/$taskId': {
      id: '/api/hermes-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/hermes-tasks/$taskId'
      preLoaderRoute: typeof ApiHermesTasksTaskIdRouteImport
      parentRoute: typeof ApiHermesTasksRoute
    }
    '/api/hermes-proxy/$': {
      id: '/api/hermes-proxy/$'
      path: '/api/hermes-proxy/$'
      fullPath: '/api/hermes-proxy/$'
      preLoaderRoute: typeof ApiHermesProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs/$jobId': {
      id: '/api/hermes-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/hermes-jobs/$jobId'
      preLoaderRoute: typeof ApiHermesJobsJobIdRouteImport
      parentRoute: typeof ApiHermesJobsRoute
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/sessions/$sessionKey/active-run': {
      id: '/api/sessions/$sessionKey/active-run'
      path: '/$sessionKey/active-run'
      fullPath: '/api/sessions/$sessionKey/active-run'
      preLoaderRoute: typeof ApiSessionsSessionKeyActiveRunRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiHermesJobsRouteChildren {
  ApiHermesJobsJobIdRoute: typeof ApiHermesJobsJobIdRoute
}

const ApiHermesJobsRouteChildren: ApiHermesJobsRouteChildren = {
  ApiHermesJobsJobIdRoute: ApiHermesJobsJobIdRoute,
}

const ApiHermesJobsRouteWithChildren = ApiHermesJobsRoute._addFileChildren(
  ApiHermesJobsRouteChildren,
)

interface ApiHermesTasksRouteChildren {
  ApiHermesTasksTaskIdRoute: typeof ApiHermesTasksTaskIdRoute
}

const ApiHermesTasksRouteChildren: ApiHermesTasksRouteChildren = {
  ApiHermesTasksTaskIdRoute: ApiHermesTasksTaskIdRoute,
}

const ApiHermesTasksRouteWithChildren = ApiHermesTasksRoute._addFileChildren(
  ApiHermesTasksRouteChildren,
)

interface ApiMemoryRouteChildren {
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryReadRoute: typeof ApiMemoryReadRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryWriteRoute: typeof ApiMemoryWriteRoute
}

const ApiMemoryRouteChildren: ApiMemoryRouteChildren = {
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryReadRoute: ApiMemoryReadRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryWriteRoute: ApiMemoryWriteRoute,
}

const ApiMemoryRouteWithChildren = ApiMemoryRoute._addFileChildren(
  ApiMemoryRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyActiveRunRoute: typeof ApiSessionsSessionKeyActiveRunRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyActiveRunRoute: ApiSessionsSessionKeyActiveRunRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsHubSearchRoute: typeof ApiSkillsHubSearchRoute
  ApiSkillsInstallRoute: typeof ApiSkillsInstallRoute
  ApiSkillsToggleRoute: typeof ApiSkillsToggleRoute
  ApiSkillsUninstallRoute: typeof ApiSkillsUninstallRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsHubSearchRoute: ApiSkillsHubSearchRoute,
  ApiSkillsInstallRoute: ApiSkillsInstallRoute,
  ApiSkillsToggleRoute: ApiSkillsToggleRoute,
  ApiSkillsUninstallRoute: ApiSkillsUninstallRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ConductorRoute: ConductorRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  OperationsRoute: OperationsRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  TerminalRoute: TerminalRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiConductorSpawnRoute: ApiConductorSpawnRoute,
  ApiConductorStopRoute: ApiConductorStopRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiCrewStatusRoute: ApiCrewStatusRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiHermesConfigRoute: ApiHermesConfigRoute,
  ApiHermesJobsRoute: ApiHermesJobsRouteWithChildren,
  ApiHermesTasksRoute: ApiHermesTasksRouteWithChildren,
  ApiHermesTasksAssigneesRoute: ApiHermesTasksAssigneesRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiLocalProvidersRoute: ApiLocalProvidersRoute,
  ApiMemoryRoute: ApiMemoryRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiStartAgentRoute: ApiStartAgentRoute,
  ApiStartHermesRoute: ApiStartHermesRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiHermesProxySplatRoute: ApiHermesProxySplatRoute,
  ApiKnowledgeConfigRoute: ApiKnowledgeConfigRoute,
  ApiKnowledgeGraphRoute: ApiKnowledgeGraphRoute,
  ApiKnowledgeListRoute: ApiKnowledgeListRoute,
  ApiKnowledgeReadRoute: ApiKnowledgeReadRoute,
  ApiKnowledgeSearchRoute: ApiKnowledgeSearchRoute,
  ApiKnowledgeSyncRoute: ApiKnowledgeSyncRoute,
  ApiMcpReloadRoute: ApiMcpReloadRoute,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiModelInfoRoute: ApiModelInfoRoute,
  ApiOauthDeviceCodeRoute: ApiOauthDeviceCodeRoute,
  ApiOauthPollTokenRoute: ApiOauthPollTokenRoute,
  ApiProfilesActivateRoute: ApiProfilesActivateRoute,
  ApiProfilesCreateRoute: ApiProfilesCreateRoute,
  ApiProfilesDeleteRoute: ApiProfilesDeleteRoute,
  ApiProfilesListRoute: ApiProfilesListRoute,
  ApiProfilesReadRoute: ApiProfilesReadRoute,
  ApiProfilesRenameRoute: ApiProfilesRenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
